(()=>{'use strict';
const $=id=>document.getElementById(id);
const LANG=(document.documentElement.lang||'en').toLowerCase().startsWith('es')?'es':'en';
const ES=LANG==='es';
const TXT={
  YOUR_TURN:ES?'TU TURNO':'YOUR TURN', WAIT:ES?'ESPERA':'WAIT', THINKING:ES?'PENSANDO':'THINKING', FINISHED:ES?'TERMINADO':'FINISHED', SOLVED:ES?'RESUELTO':'SOLVED', UNSOLVED:ES?'SIN RESOLVER':'UNSOLVED',
  ATTEMPT:ES?'INTENTO':'ATTEMPT', PROFESSIONAL:ES?'PROFESIONAL':'PROFESSIONAL', AMATEUR:'AMATEUR',
  CHOOSE:ES?'Pulsa o arrastra · negra = color y posición · blanca = color en otra posición.':'Click or drag · black = color and position · white = color in another position.',
  NORI_LOCKING:ES?'NORI está fijando su jugada…':'NORI is locking its move…', NORI_LOCKED:ES?'Jugada fijada. El árbitro calcula ahora las pistas.':'Move locked. The referee now calculates the clues.',
  COPY_OK:ES?'ENLACE COPIADO':'LINK COPIED', COPY_FAIL:ES?'COPIA EL ENLACE DEL NAVEGADOR':'COPY THE BROWSER LINK', SOUND_ON:ES?'SÍ':'ON', SOUND_OFF:'OFF',
  RESULT_HWIN:ES?'VENTAJA HUMANA':'HUMAN ADVANTAGE', RESULT_BWIN:ES?'VENTAJA NORI':'NORI ADVANTAGE', RESULT_TIE:ES?'EMPATE':'DRAW', RESULT_NONE:ES?'SIN GANADOR':'NO WINNER',
  RESULT_BY_ATTEMPTS:ES?'Menos intentos para resolver el patrón.':'Fewer attempts to solve the pattern.', RESULT_BY_TIME:ES?'Mismos intentos: decide el tiempo.':'Same number of attempts: time breaks the tie.', RESULT_ONLY_H:ES?'Solo tú resolviste el código contrario.':'Only you solved the opposing code.', RESULT_ONLY_B:ES?'Solo NORI resolvió el código contrario.':'Only NORI solved the opposing code.', RESULT_NEITHER:ES?'Ninguno resolvió el código contrario en doce intentos.':'Neither side solved the opposing code in twelve attempts.',
  TRIES:n=>ES?`${n} INTENTOS`:`${n} ATTEMPTS`, NO_SOLVE:ES?'SIN RESOLVER':'UNSOLVED',
  LEVEL_CHANGED:ES?'Nivel cambiado. Crea un nuevo código para iniciar otro duelo.':'Level changed. Create a new code to start another duel.',
  HUMAN_DONE_CONTINUE:ES?'Has terminado. NORI continúa hasta cerrar su partida.':'You are finished. NORI continues until its game is closed.', BOT_DONE_CONTINUE:ES?'NORI ha terminado. Tú puedes seguir hasta cerrar tu partida.':'NORI is finished. You may continue until your game is closed.',
  HINT_READY:ES?'Revela una ficha exacta del código de NORI.':'Reveal one exact peg from NORI\'s code.', HINT_USED:ES?'PISTA USADA':'HINT USED',
  HINT_TITLE:ES?'USAR PISTA':'USE HINT', HINT_MSG:ES?'¿Mostrar una posición exacta del código de NORI? Solo puedes usar una pista por partida.':'Reveal one exact position from NORI\'s code? You can use only one hint per game.',
  HINT_DONE:(p)=>ES?`Pista revelada: posición ${p}.`:`Hint revealed: position ${p}.`,
  SOLVE_TITLE:ES?'REVELAR SOLUCIÓN':'REVEAL SOLUTION', SOLVE_MSG:ES?'¿Revelar ahora los dos códigos y cerrar la partida?':'Reveal both codes now and end the duel?',
  FINISH_TITLE:ES?'TERMINAR DUELO':'FINISH DUEL', FINISH_MSG:ES?'¿Terminar ahora el duelo? Los jugadores que no hayan resuelto aparecerán como sin resolver.':'Finish the duel now? Players who have not solved will be shown as unsolved.',
  RESTART_TITLE:ES?'NUEVA PARTIDA':'NEW GAME', RESTART_MSG:ES?'¿Empezar una nueva partida? Se perderá el duelo actual.':'Start a new game? The current duel will be lost.',
  DIALOG_CANCEL:ES?'CANCELAR':'CANCEL', DIALOG_ACCEPT:ES?'ACEPTAR':'ACCEPT', DIALOG_CONFIRM:ES?'CONFIRMACIÓN':'CONFIRMATION',
  HINT_LEFT:ES?'1 DISPONIBLE':'1 AVAILABLE', HINT_NONE:ES?'0 DISPONIBLES':'0 AVAILABLE',
  MACHINE_HINT_HIDDEN:ES?'Código de NORI oculto · pista opcional':'NORI code hidden · optional hint'
};
const LEN=5,COLOR_COUNT=8,MAX=12,TOTAL=32768,SAVE_KEY='eidos-consciencia-settings-v1';
const SHARED=window.EIDOS_SHARED_CONTENT||{images:[],quotes:[]};
const MANIFEST=Array.isArray(window.EIDOS_IMAGE_MANIFEST)?window.EIDOS_IMAGE_MANIFEST:[];
function galleryUrl(item){if(!item)return'';const raw=typeof item==='string'?item:item.url;if(!raw)return'';return /^(?:https?:)?\/\//.test(raw)||raw.startsWith('/')?raw:'/gallery/'+String(raw).replace(/^\.?\//,'');}
const BG_IMAGES=MANIFEST.length?MANIFEST.map(galleryUrl).filter(Boolean):(Array.isArray(SHARED.images)?SHARED.images.filter(Boolean):[]);
const BG_ROOT=$('eidos-shared-bg'),BG_LAYERS=[$('eidos-bg-a'),$('eidos-bg-b')];
let bgDeck=[],activeBg=0,lastBg=-1,badBg=new Set();
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function refillBg(){bgDeck=shuffle(BG_IMAGES.map((_,i)=>i).filter(i=>!badBg.has(i)));if(bgDeck.length>1&&bgDeck[0]===lastBg)[bgDeck[0],bgDeck[1]]=[bgDeck[1],bgDeck[0]];}
function changeBackground(attempt=0){if(!BG_IMAGES.length||badBg.size>=BG_IMAGES.length)return;if(!bgDeck.length)refillBg();if(!bgDeck.length)return;const idx=bgDeck.shift(),next=1-activeBg,img=BG_LAYERS[next],old=BG_LAYERS[activeBg];img.onload=()=>{img.onload=img.onerror=null;old.classList.remove('active');img.classList.add('active');activeBg=next;lastBg=idx;document.documentElement.style.setProperty('--shared-image',`url("${img.src}")`);};img.onerror=()=>{img.onload=img.onerror=null;badBg.add(idx);img.removeAttribute('src');if(attempt<BG_IMAGES.length-1)changeBackground(attempt+1);};img.src=BG_IMAGES[idx];}

let level='professional',soundOn=true,audioCtx=null;
let secretDraft=emptySlots(),humanSecret=null,machineSecret=null,currentGuess=emptySlots(),machineHints=Array(LEN).fill(null),hintAvailable=true;
let humanHistory=[],botHistory=[],botLive=[];
let humanDone=false,botDone=false,started=false;
let activeClock=null,lastClockStamp=0,humanMs=0,botMs=0,clockTimer=null;
let aiWorker=null,workerPending=null,levelChangedWhileActive=false;
let dialogResolver=null;

function readSettings(){try{const v=JSON.parse(localStorage.getItem(SAVE_KEY)||'{}');if(v.level==='amateur'||v.level==='professional')level=v.level;if(v.sound===false)soundOn=false;}catch(e){}}
function saveSettings(){try{localStorage.setItem(SAVE_KEY,JSON.stringify({level,sound:soundOn}));}catch(e){}}
readSettings();

function emptySlots(){return Array(LEN).fill(null);} function filledCount(a){return a.reduce((n,v)=>n+(Number.isInteger(v)?1:0),0);} function completeSlots(a){return filledCount(a)===LEN;} function firstEmpty(a){return a.findIndex(v=>!Number.isInteger(v));}
function codeIndex(a){let n=0;for(let i=0;i<LEN;i++)n=n*COLOR_COUNT+a[i];return n;} function codeArray(idx){const a=Array(LEN);for(let p=LEN-1;p>=0;p--){a[p]=idx%COLOR_COUNT;idx=Math.floor(idx/COLOR_COUNT);}return a;} function randomCode(){return Math.floor(Math.random()*TOTAL);}
function score(secretIdx,guessIdx){const s=codeArray(secretIdx),g=codeArray(guessIdx);let black=0;const sc=Array(COLOR_COUNT).fill(0),gc=Array(COLOR_COUNT).fill(0);for(let i=0;i<LEN;i++){if(s[i]===g[i])black++;else{sc[s[i]]++;gc[g[i]]++;}}let white=0;for(let c=0;c<COLOR_COUNT;c++)white+=Math.min(sc[c],gc[c]);return{black,white};}
function fmt(ms){ms=Math.max(0,ms);const m=Math.floor(ms/60000),s=Math.floor(ms%60000/1000),d=Math.floor(ms%1000/100);return String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')+'.'+d;}
function commitClock(){if(activeClock&&lastClockStamp){const d=performance.now()-lastClockStamp;if(activeClock==='human')humanMs+=d;else botMs+=d;}lastClockStamp=activeClock?performance.now():0;}
function setClock(next){commitClock();activeClock=next;lastClockStamp=next?performance.now():0;renderClocks();}
function renderClocks(){let h=humanMs,b=botMs;if(activeClock&&lastClockStamp){const d=performance.now()-lastClockStamp;if(activeClock==='human')h+=d;else b+=d;}$('humanClock').textContent=fmt(h);$('botClock').textContent=fmt(b);$('humanClockBox').classList.toggle('active',activeClock==='human');$('botClockBox').classList.toggle('active',activeClock==='bot');}
function startClockTimer(){clearInterval(clockTimer);clockTimer=setInterval(renderClocks,100);}
function beep(freq=520,dur=.045,vol=.025){if(!soundOn)return;try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime;o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+dur);}catch(e){}}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}

function pegHTML(c,extra=''){return `<i class="peg c${c} ${extra}"></i>`;} function emptyPegHTML(){return '<i class="peg empty"></i>';} function feedbackHTML(s,animate=false){let out='';for(let i=0;i<s.black;i++)out+=`<i class="hintpeg black ${animate?'feedback-in':''}" title="${ES?'Color y posición correctos':'Correct color and position'}"></i>`;for(let i=0;i<s.white;i++)out+=`<i class="hintpeg white ${animate?'feedback-in':''}" title="${ES?'Color correcto, posición incorrecta':'Correct color, wrong position'}"></i>`;for(let i=s.black+s.white;i<LEN;i++)out+=`<i class="hintpeg" title="${ES?'Sin coincidencia adicional':'No additional match'}"></i>`;return out;}
function rowHTML(n,item,live,active){let code='',fb='';if(item){code=codeArray(item.guess).map(c=>pegHTML(c)).join('');fb=feedbackHTML(item.score);}else if(live){code=live.map(c=>pegHTML(c,'fade-in')).join('')+Array.from({length:LEN-live.length},emptyPegHTML).join('');fb=Array.from({length:LEN},()=>'<i class="hintpeg"></i>').join('');}else{code=Array.from({length:LEN},emptyPegHTML).join('');fb=Array.from({length:LEN},()=>'<i class="hintpeg"></i>').join('');}return `<div class="attempt ${active?'active':''}"><span class="attempt-no">${n}</span><div class="code-pegs">${code}</div><div class="feedback">${fb}</div></div>`;}
function renderBoards(){let h='',b='';for(let i=0;i<MAX;i++){h+=rowHTML(i+1,humanHistory[i],null,!humanDone&&activeClock==='human'&&i===humanHistory.length);b+=rowHTML(i+1,botHistory[i],i===botHistory.length&&botLive.length?botLive:null,!botDone&&activeClock==='bot'&&i===botHistory.length);}$('humanRows').innerHTML=h;$('botRows').innerHTML=b;}
function setStatus(el,text,kind=''){el.textContent=text;el.className='status '+kind;} function setInstruction(text){$('instructionText').textContent=text;}

function wireDropSlot(node,array,index,kind){node.addEventListener('dragover',e=>{e.preventDefault();node.classList.add('drop-target');});node.addEventListener('dragleave',()=>node.classList.remove('drop-target'));node.addEventListener('drop',e=>{e.preventDefault();node.classList.remove('drop-target');if(kind==='guess'&&(activeClock!=='human'||humanDone))return;let data;try{data=JSON.parse(e.dataTransfer.getData('text/plain')||'{}');}catch(_){data={};}if(!Number.isInteger(data.color))return;if(data.kind===kind&&Number.isInteger(data.index)){if(data.index===index)return;const old=array[index];array[index]=data.color;array[data.index]=Number.isInteger(old)?old:null;}else array[index]=data.color;beep(420+data.color*28,.035,.018);kind==='secret'?renderSecretBuilder():renderCurrentGuess();if(kind==='guess')updateReveal();});}
function wireDragPeg(node,array,index,kind){if(!Number.isInteger(array[index]))return;node.draggable=true;node.addEventListener('dragstart',e=>{e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',JSON.stringify({kind,index,color:array[index]}));node.classList.add('dragging');});node.addEventListener('dragend',()=>node.classList.remove('dragging'));}
function wirePaletteDrop(el,array,kind){el.addEventListener('dragover',e=>{e.preventDefault();el.classList.add('drop-remove');});el.addEventListener('dragleave',()=>el.classList.remove('drop-remove'));el.addEventListener('drop',e=>{el.classList.remove('drop-remove');let d={};try{d=JSON.parse(e.dataTransfer.getData('text/plain')||'{}');}catch(_){}if(d.kind!==kind||!Number.isInteger(d.index))return;e.preventDefault();array[d.index]=null;beep(280,.03,.018);kind==='secret'?renderSecretBuilder():renderCurrentGuess();if(kind==='guess')updateReveal();});}
function renderCurrentGuess(){const el=$('currentGuess');el.innerHTML='';for(let i=0;i<LEN;i++){const node=document.createElement('button');node.type='button';const filled=Number.isInteger(currentGuess[i]);node.className='peg '+(filled?'c'+currentGuess[i]:'empty');node.setAttribute('aria-label',(ES?'Posición ':'Position ')+(i+1)+(filled?(ES?'. Pulsa para quitar o arrastra para mover.':'. Click to remove or drag to move.'):(ES?'. Arrastra aquí un color.':'. Drag a color here.')));if(filled)node.addEventListener('click',()=>{if(activeClock!=='human'||humanDone)return;currentGuess[i]=null;beep(280,.03,.018);renderCurrentGuess();updateReveal();});wireDragPeg(node,currentGuess,i,'guess');wireDropSlot(node,currentGuess,i,'guess');el.appendChild(node);}$('confirmButton').disabled=!completeSlots(currentGuess)||activeClock!=='human'||humanDone;$('eraseButton').disabled=!filledCount(currentGuess)||activeClock!=='human'||humanDone;$('attemptLabel').textContent=`${TXT.ATTEMPT} ${Math.min(MAX,humanHistory.length+1)} / ${MAX}`;updateControlStates();}
function renderPalette(){const el=$('palette');el.innerHTML='';for(let c=0;c<COLOR_COUNT;c++){const b=document.createElement('button');b.type='button';b.className='colorbtn c'+c;b.draggable=true;b.setAttribute('aria-label',(ES?'Color ':'Color ')+(c+1));b.addEventListener('dragstart',e=>{e.dataTransfer.effectAllowed='copy';e.dataTransfer.setData('text/plain',JSON.stringify({kind:'palette',color:c}));});b.addEventListener('click',()=>{if(activeClock!=='human'||humanDone)return;const i=firstEmpty(currentGuess);if(i<0)return;currentGuess[i]=c;beep(360+c*35,.035,.018);renderCurrentGuess();updateReveal();});el.appendChild(b);} wirePaletteDrop(el,currentGuess,'guess');}
function renderSecretBuilder(){const slots=$('secretSlots');slots.innerHTML='';for(let i=0;i<LEN;i++){const b=document.createElement('button');b.type='button';const filled=Number.isInteger(secretDraft[i]);b.className='peg '+(filled?'c'+secretDraft[i]:'empty');b.setAttribute('aria-label',(ES?'Posición ':'Position ')+(i+1)+(filled?(ES?'. Pulsa para quitar o arrastra para mover.':'. Click to remove or drag to move.'):(ES?'. Arrastra aquí un color.':'. Drag a color here.')));if(filled)b.addEventListener('click',()=>{secretDraft[i]=null;beep(280,.03,.018);renderSecretBuilder();});wireDragPeg(b,secretDraft,i,'secret');wireDropSlot(b,secretDraft,i,'secret');slots.appendChild(b);}const p=$('secretPalette');p.innerHTML='';for(let c=0;c<COLOR_COUNT;c++){const b=document.createElement('button');b.type='button';b.className='colorbtn c'+c;b.draggable=true;b.setAttribute('aria-label',(ES?'Color ':'Color ')+(c+1));b.addEventListener('dragstart',e=>{e.dataTransfer.effectAllowed='copy';e.dataTransfer.setData('text/plain',JSON.stringify({kind:'palette',color:c}));});b.addEventListener('click',()=>{const i=firstEmpty(secretDraft);if(i<0)return;secretDraft[i]=c;beep(380+c*32,.035,.018);renderSecretBuilder();});p.appendChild(b);}wirePaletteDrop(p,secretDraft,'secret');$('lockSecret').disabled=!completeSlots(secretDraft);$('clearSecret').disabled=!filledCount(secretDraft);}
function renderHumanSecretBar(){const el=$('humanSecretBar');if(!el)return;if(humanSecret===null){el.innerHTML=Array.from({length:LEN},()=>'<i class="secret-dot"></i>').join('');return;}el.innerHTML=codeArray(humanSecret).map(c=>`<i class="mini-secret c${c}"></i>`).join('');}
function renderMachineHintBar(){const el=$('machineHintBar');if(!el)return;el.innerHTML=machineHints.map(v=>Number.isInteger(v)?`<i class="mini-secret c${v}"></i>`:'<i class="secret-dot"></i>').join('');$('hintState').textContent=hintAvailable?TXT.HINT_LEFT:TXT.HINT_NONE;}
function progressRatio(history,solved,liveCount=0){if(solved)return 1;let best=0,total=0;for(const item of history){const s=item.score;const strength=(s.black + s.white*0.62)/LEN;if(strength>best)best=strength;total+=strength;}const attempts=history.length/MAX;const live=liveCount?Math.min(.08,liveCount/(LEN*20)):0;return Math.max(0,Math.min(1,best*.62+Math.min(.2,total/(MAX*1.7))+attempts*.18+live));}
function updateReveal(force=null){const humanRatio=force===null?progressRatio(humanHistory,humanDone,filledCount(currentGuess)):Math.max(0,Math.min(1,force));const botRatio=force===null?progressRatio(botHistory,botDone,botLive.length):Math.max(0,Math.min(1,force));const pct=Math.round(((humanRatio+botRatio)/2)*100);$('revealFill').style.width=pct+'%';$('revealValue').textContent=pct+'%';document.documentElement.style.setProperty('--human-clear',humanRatio.toFixed(3));document.documentElement.style.setProperty('--bot-clear',botRatio.toFixed(3));if(BG_ROOT){const avg=(humanRatio+botRatio)/2;BG_ROOT.style.setProperty('--bg-opacity',(.12+avg*.34).toFixed(3));BG_ROOT.style.setProperty('--bg-blur',(8*(1-avg)).toFixed(2)+'px');BG_ROOT.style.setProperty('--bg-bright',(.42+avg*.36).toFixed(3));}const hb=$('humanBoard'),bb=$('botBoard');if(hb)hb.style.setProperty('--board-clear',humanRatio.toFixed(3));if(bb)bb.style.setProperty('--board-clear',botRatio.toFixed(3));}
function updateControlStates(){$('soundState').textContent=soundOn?TXT.SOUND_ON:TXT.SOUND_OFF;$('hintButton').disabled=!started||humanDone||!hintAvailable||activeClock==='bot';$('solveButton').disabled=!started||activeClock==='bot';$('finishButton').disabled=!started||activeClock==='bot';$('restartButton').disabled=activeClock==='bot';$('levelButton').disabled=activeClock==='bot';}
function showScreen(id){for(const s of document.querySelectorAll('.screen'))s.classList.remove('open');if(id)$(id).classList.add('open');}
function updateLevelUI(){const pro=level==='professional';$('professionalChoice').classList.toggle('selected',pro);$('amateurChoice').classList.toggle('selected',!pro);$('levelMini').textContent=pro?TXT.PROFESSIONAL:TXT.AMATEUR;$('levelState').textContent=pro?'PRO':'AM';$('menuLevelText').textContent=pro?TXT.PROFESSIONAL:TXT.AMATEUR;$('startLevelButton').textContent=(ES?'NIVEL: ':'LEVEL: ')+(pro?TXT.PROFESSIONAL:TXT.AMATEUR);updateControlStates();}
async function askDialog(title,msg,confirmText=TXT.DIALOG_ACCEPT,cancelText=TXT.DIALOG_CANCEL,danger=false){setClock(null);$('dialogTitle').textContent=title;$('dialogMessage').textContent=msg;$('dialogKicker').textContent=TXT.DIALOG_CONFIRM;$('dialogConfirm').textContent=confirmText;$('dialogCancel').textContent=cancelText;$('dialogCard').classList.toggle('danger',danger);showScreen('dialogScreen');return new Promise(resolve=>{dialogResolver=resolve;});}
function closeDialog(ok){showScreen(null);if(dialogResolver){const fn=dialogResolver;dialogResolver=null;fn(ok);} }
function resumeHumanIfNeeded(){if(started&&!humanDone&&activeClock!=='bot'){setClock('human');renderCurrentGuess();}}

function workerSource(){return `
'use strict';
const LEN=5,C=8,N=32768;
const digits=new Uint8Array(N*LEN),counts=new Uint8Array(N*C);
for(let idx=0;idx<N;idx++){let n=idx;for(let p=LEN-1;p>=0;p--){const c=n%C;n=Math.floor(n/C);digits[idx*LEN+p]=c;counts[idx*C+c]++;}}
let candidates=[],level='professional',history=[];
function idxOf(a){let n=0;for(const v of a)n=n*C+v;return n;}
function scoreKey(si,gi){let black=0,common=0;for(let p=0;p<LEN;p++)if(digits[si*LEN+p]===digits[gi*LEN+p])black++;for(let c=0;c<C;c++)common+=Math.min(counts[si*C+c],counts[gi*C+c]);return black*6+(common-black);}
function spaced(a,k,phase=0){if(a.length<=k)return a.slice();const out=[],step=a.length/k;for(let i=0;i<k;i++)out.push(a[Math.min(a.length-1,Math.floor((i+phase)*step)%a.length)]);return [...new Set(out)];}
function choosePro(){ if(history.length===0)return idxOf([0,0,1,2,3]); if(candidates.length<=1)return candidates[0]; const solutionSample=candidates.length>5200?spaced(candidates,360,.17):candidates.length>2400?spaced(candidates,620,.31):candidates; let pool; if(candidates.length>6000)pool=spaced(candidates,150,.11); else if(candidates.length>1800)pool=spaced(candidates,260,.23); else if(candidates.length>650)pool=spaced(candidates,380,.07); else pool=candidates.slice(); const buckets=new Uint32Array(36); let best=pool[0],bestExpected=Infinity,bestWorst=Infinity,bestDistinct=-1; for(const g of pool){buckets.fill(0);for(const s of solutionSample)buckets[scoreKey(s,g)]++;let ss=0,worst=0;for(let i=0;i<36;i++){const n=buckets[i];ss+=n*n;if(n>worst)worst=n;}let distinct=0,seen=0;for(let p=0;p<LEN;p++){const bit=1<<digits[g*LEN+p];if(!(seen&bit)){seen|=bit;distinct++;}} if(ss<bestExpected||(ss===bestExpected&&worst<bestWorst)||(ss===bestExpected&&worst===bestWorst&&distinct>bestDistinct)){best=g;bestExpected=ss;bestWorst=worst;bestDistinct=distinct;}} return best; }
function chooseAmateur(){ if(history.length===0)return idxOf([0,1,2,3,4]); if(candidates.length<=1)return candidates[0]; const pool=spaced(candidates,Math.min(56,candidates.length),.37); const prev=history[history.length-1].guess; let best=pool[0],bestV=-1e9; for(const g of pool){let same=0,overlap=0;const pc=new Uint8Array(C),gc=new Uint8Array(C);for(let p=0;p<LEN;p++){const a=digits[prev*LEN+p],b=digits[g*LEN+p];if(a===b)same++;pc[a]++;gc[b]++;}for(let c=0;c<C;c++)overlap+=Math.min(pc[c],gc[c]);const v=same*.75+overlap*.22;if(v>bestV){bestV=v;best=g;}} return best; }
function filter(g,k){const out=[];for(const s of candidates)if(scoreKey(s,g)===k)out.push(s);candidates=out;}
onmessage=e=>{const m=e.data||{};if(m.type==='init'){level=m.level==='amateur'?'amateur':'professional';candidates=Array.from({length:N},(_,i)=>i);history=[];postMessage({type:'ready',count:candidates.length});return;}if(m.type==='request'){const guess=level==='professional'?choosePro():chooseAmateur();postMessage({type:'guess',guess,count:candidates.length});return;}if(m.type==='feedback'){const key=(m.black|0)*6+(m.white|0);filter(m.guess|0,key);history.push({guess:m.guess|0,key});postMessage({type:'filtered',count:candidates.length});}};
`;}
function createAI(){destroyAI();try{const blob=new Blob([workerSource()],{type:'application/javascript'}),url=URL.createObjectURL(blob);aiWorker=new Worker(url);URL.revokeObjectURL(url);aiWorker.onmessage=e=>{const m=e.data||{};if(m.type==='guess'&&workerPending){const p=workerPending;workerPending=null;p.resolve(m.guess);}};aiWorker.onerror=e=>{console.error('NORI worker error',e);if(workerPending){workerPending.reject(e);workerPending=null;}};aiWorker.postMessage({type:'init',level});}catch(e){console.error(e);aiWorker=null;}}
function destroyAI(){if(aiWorker){aiWorker.terminate();aiWorker=null;}workerPending=null;}
function requestBotGuess(){return new Promise((resolve,reject)=>{if(!aiWorker){reject(new Error('AI unavailable'));return;}workerPending={resolve,reject};aiWorker.postMessage({type:'request'});});}
function sendFeedback(guess,s){if(aiWorker)aiWorker.postMessage({type:'feedback',guess,black:s.black,white:s.white});}

function resetState(){setClock(null);clearInterval(clockTimer);humanSecret=null;machineSecret=null;currentGuess=emptySlots();humanHistory=[];botHistory=[];botLive=[];machineHints=Array(LEN).fill(null);hintAvailable=true;humanDone=false;botDone=false;started=false;humanMs=0;botMs=0;levelChangedWhileActive=false;destroyAI();renderClocks();renderHumanSecretBar();renderMachineHintBar();renderBoards();renderCurrentGuess();updateReveal(0);setStatus($('humanStatus'),TXT.YOUR_TURN);setStatus($('botStatus'),TXT.WAIT);updateControlStates();}
function prepareSecret(){resetState();secretDraft=emptySlots();renderSecretBuilder();showScreen('secretScreen');changeBackground();}
function beginGame(){if(!completeSlots(secretDraft))return;humanSecret=codeIndex(secretDraft);machineSecret=randomCode();secretDraft=emptySlots();currentGuess=emptySlots();humanHistory=[];botHistory=[];botLive=[];machineHints=Array(LEN).fill(null);hintAvailable=true;humanDone=false;botDone=false;started=true;humanMs=botMs=0;createAI();showScreen(null);renderHumanSecretBar();renderMachineHintBar();renderBoards();renderCurrentGuess();renderPalette();updateReveal(0);setStatus($('humanStatus'),TXT.YOUR_TURN);setStatus($('botStatus'),TXT.WAIT);setInstruction(TXT.CHOOSE);setClock('human');startClockTimer();updateControlStates();beep(620,.08,.03);}
async function humanSubmit(){if(!started||humanDone||activeClock!=='human'||!completeSlots(currentGuess))return;const gi=codeIndex(currentGuess);setClock(null);const s=score(machineSecret,gi);humanHistory.push({guess:gi,score:s});currentGuess=emptySlots();renderBoards();renderCurrentGuess();updateReveal();beep(s.black===LEN?820:520,.07,.025);if(s.black===LEN){humanDone=true;setStatus($('humanStatus'),TXT.SOLVED,'done');}else if(humanHistory.length>=MAX){humanDone=true;setStatus($('humanStatus'),TXT.UNSOLVED,'fail');}if(humanDone&&botDone){finishDuel();return;}await botTurn();}
async function botTurn(){if(!started||botDone){continueAfterTurn();return;}if(botHistory.length>=MAX){botDone=true;setStatus($('botStatus'),TXT.UNSOLVED,'fail');continueAfterTurn();return;}setClock('bot');setStatus($('botStatus'),TXT.THINKING);if(!humanDone)setStatus($('humanStatus'),TXT.WAIT);updateControlStates();setInstruction(level==='professional'?(ES?'NORI compara las soluciones compatibles y busca una jugada informativa.':'NORI compares compatible solutions and searches for an informative move.'):(ES?'NORI descarta lo imposible y prepara una jugada lógica.':'NORI eliminates impossible codes and prepares a logical move.'));let committed;try{committed=await requestBotGuess();}catch(e){botDone=true;setStatus($('botStatus'),ES?'ERROR MOTOR':'ENGINE ERROR','fail');continueAfterTurn();return;} botLive=[];renderBoards();const arr=codeArray(committed);setInstruction(TXT.NORI_LOCKING);for(const c of arr){botLive.push(c);renderBoards();updateReveal();beep(330+c*32,.035,.015);await sleep(190);}await sleep(260);setInstruction(TXT.NORI_LOCKED);const s=score(humanSecret,committed);botHistory.push({guess:committed,score:s});botLive=[];sendFeedback(committed,s);renderBoards();updateReveal();beep(s.black===LEN?840:470,.075,.025);await sleep(330);if(s.black===LEN){botDone=true;setStatus($('botStatus'),TXT.SOLVED,'done');setClock(null);}else if(botHistory.length>=MAX){botDone=true;setStatus($('botStatus'),TXT.UNSOLVED,'fail');setClock(null);}continueAfterTurn();}
function continueAfterTurn(){if(!started)return;if(humanDone&&botDone){finishDuel();return;}if(humanDone&&!botDone){setClock(null);setStatus($('humanStatus'),TXT.FINISHED,'done');setInstruction(TXT.HUMAN_DONE_CONTINUE);updateControlStates();setTimeout(()=>botTurn(),420);return;}if(botDone&&!humanDone){setClock('human');setStatus($('botStatus'),TXT.FINISHED,botHistory.some(x=>x.score.black===LEN)?'done':'fail');setStatus($('humanStatus'),TXT.YOUR_TURN);setInstruction(TXT.BOT_DONE_CONTINUE);renderCurrentGuess();updateControlStates();return;}setClock('human');setStatus($('humanStatus'),TXT.YOUR_TURN);setStatus($('botStatus'),TXT.WAIT);setInstruction(TXT.CHOOSE);renderCurrentGuess();updateControlStates();}
function resultWinner(){const hSolved=humanHistory.some(x=>x.score.black===LEN),bSolved=botHistory.some(x=>x.score.black===LEN);if(hSolved&&!bSolved)return{winner:'human',why:TXT.RESULT_ONLY_H};if(bSolved&&!hSolved)return{winner:'bot',why:TXT.RESULT_ONLY_B};if(!hSolved&&!bSolved)return{winner:'none',why:TXT.RESULT_NEITHER};if(humanHistory.length<botHistory.length)return{winner:'human',why:TXT.RESULT_BY_ATTEMPTS};if(botHistory.length<humanHistory.length)return{winner:'bot',why:TXT.RESULT_BY_ATTEMPTS};if(humanMs<botMs)return{winner:'human',why:TXT.RESULT_BY_TIME};if(botMs<humanMs)return{winner:'bot',why:TXT.RESULT_BY_TIME};return{winner:'tie',why:TXT.RESULT_BY_TIME};}
function fillCode(el,idx){el.innerHTML=codeArray(idx).map(c=>pegHTML(c)).join('');}
function finishDuel(){if(!started && humanSecret===null)return;setClock(null);clearInterval(clockTimer);started=false;humanDone=true;botDone=true;destroyAI();updateReveal(1);const hSolved=humanHistory.some(x=>x.score.black===LEN),bSolved=botHistory.some(x=>x.score.black===LEN),r=resultWinner();$('verdictText').textContent=r.winner==='human'?TXT.RESULT_HWIN:r.winner==='bot'?TXT.RESULT_BWIN:r.winner==='tie'?TXT.RESULT_TIE:TXT.RESULT_NONE;$('humanResult').textContent=hSolved?TXT.TRIES(humanHistory.length):TXT.NO_SOLVE;$('botResult').textContent=bSolved?TXT.TRIES(botHistory.length):TXT.NO_SOLVE;$('humanResultTime').textContent=fmt(humanMs);$('botResultTime').textContent=fmt(botMs);$('resultDetail').textContent=r.why;fillCode($('machineCodeReveal'),machineSecret);fillCode($('humanCodeReveal'),humanSecret);showScreen('resultScreen');updateControlStates();beep(r.winner==='human'?760:r.winner==='bot'?520:640,.16,.035);}

function chooseLevel(next){if(next!==level){level=next;saveSettings();updateLevelUI();if(started)levelChangedWhileActive=true;}else updateLevelUI();}
function difficultyBack(){showScreen(null);if(levelChangedWhileActive){prepareSecret();setInstruction(TXT.LEVEL_CHANGED);return;}if(!started){showScreen('startScreen');return;}if(!humanDone){setClock('human');renderCurrentGuess();updateControlStates();}}
async function restartRequested(){if(started){const ok=await askDialog(TXT.RESTART_TITLE,TXT.RESTART_MSG,TXT.DIALOG_ACCEPT,TXT.DIALOG_CANCEL,true);if(!ok){resumeHumanIfNeeded();return;}}prepareSecret();}
async function hintRequested(){if(!started||humanDone||!hintAvailable||activeClock==='bot')return;const ok=await askDialog(TXT.HINT_TITLE,TXT.HINT_MSG,TXT.DIALOG_ACCEPT,TXT.DIALOG_CANCEL,false);if(!ok){resumeHumanIfNeeded();return;}const open=[];for(let i=0;i<LEN;i++)if(!Number.isInteger(machineHints[i]))open.push(i);if(!open.length){hintAvailable=false;renderMachineHintBar();updateControlStates();resumeHumanIfNeeded();return;}const pick=open[Math.floor(Math.random()*open.length)];machineHints[pick]=codeArray(machineSecret)[pick];hintAvailable=false;renderMachineHintBar();setInstruction(TXT.HINT_DONE(pick+1));updateControlStates();beep(700,.08,.03);resumeHumanIfNeeded();}
async function solveRequested(){if(!started||activeClock==='bot')return;const ok=await askDialog(TXT.SOLVE_TITLE,TXT.SOLVE_MSG,TXT.DIALOG_ACCEPT,TXT.DIALOG_CANCEL,true);if(!ok){resumeHumanIfNeeded();return;}finishDuel();}
async function finishRequested(){if(!started||activeClock==='bot')return;const ok=await askDialog(TXT.FINISH_TITLE,TXT.FINISH_MSG,TXT.DIALOG_ACCEPT,TXT.DIALOG_CANCEL,true);if(!ok){resumeHumanIfNeeded();return;}humanDone=true;botDone=true;finishDuel();}

$('dialogCancel').addEventListener('click',()=>closeDialog(false)); $('dialogConfirm').addEventListener('click',()=>closeDialog(true));
$('startButton').addEventListener('click',()=>{beep();prepareSecret();});
$('startLevelButton').addEventListener('click',()=>showScreen('difficultyScreen'));
$('copyLinkButton').addEventListener('click',async()=>{const old=$('copyLinkButton').textContent;try{await navigator.clipboard.writeText(location.href);$('copyLinkButton').textContent=TXT.COPY_OK;}catch(e){$('copyLinkButton').textContent=TXT.COPY_FAIL;}setTimeout(()=>$('copyLinkButton').textContent=old,1500);});
$('professionalChoice').addEventListener('click',()=>{beep(650);chooseLevel('professional');}); $('amateurChoice').addEventListener('click',()=>{beep(480);chooseLevel('amateur');}); $('difficultyBack').addEventListener('click',difficultyBack);
$('clearSecret').addEventListener('click',()=>{secretDraft=emptySlots();renderSecretBuilder();beep(280);}); $('lockSecret').addEventListener('click',beginGame);
$('eraseButton').addEventListener('click',()=>{currentGuess=emptySlots();renderCurrentGuess();updateReveal();beep(280);}); $('confirmButton').addEventListener('click',humanSubmit);
$('menuButton').addEventListener('click',()=>{if(started&&activeClock==='bot')return;if(started){setClock(null);showScreen('menuScreen');}else showScreen('startScreen');});
$('resumeButton').addEventListener('click',()=>{showScreen(null);if(!humanDone){setClock('human');renderCurrentGuess();updateControlStates();}else if(!botDone)botTurn();});
$('menuRestart').addEventListener('click',restartRequested); $('menuLevel').addEventListener('click',()=>showScreen('difficultyScreen'));
$('restartButton').addEventListener('click',restartRequested); $('levelButton').addEventListener('click',()=>{if(activeClock==='bot')return;if(started)setClock(null);showScreen('difficultyScreen');});
$('soundButton').addEventListener('click',()=>{soundOn=!soundOn;saveSettings();updateControlStates();if(soundOn)beep(620);}); $('hintButton').addEventListener('click',hintRequested); $('solveButton').addEventListener('click',solveRequested); $('finishButton').addEventListener('click',finishRequested); $('againButton').addEventListener('click',prepareSecret);

updateLevelUI(); renderPalette(); renderBoards(); renderCurrentGuess(); renderSecretBuilder(); renderHumanSecretBar(); renderMachineHintBar(); updateReveal(0); changeBackground();
})();